version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "order"
    ports:
      - "5432:5432"

  nats-streaming:
    image: nats-streaming:latest
    container_name: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"