version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "order"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats-streaming:
    container_name: nats-streaming
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  consumer:
    container_name: consumer
    build:
      context: .
      dockerfile: docker/consumer.Dockerfile
    depends_on:
      - postgres
      - nats-streaming
    ports:
      - "8080:8080"
    volumes:
      - .env:/project/.env
      - ./web:/project/web

  producer:
    container_name: producer
    build:
      context: .
      dockerfile: docker/producer.Dockerfile
    depends_on:
      - nats-streaming
    volumes:
      - .env:/project/.env
      - ./schema:/project/schema

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  postgres_data: